# Generated by Django 4.0.5 on 2022-07-08 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bugType', models.CharField(max_length=12)),
                ('assignTo', models.CharField(max_length=12)),
                ('priorityLevel', models.CharField(choices=[('S', 'S'), ('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('status', models.CharField(max_length=12)),
                ('summaryTitle', models.CharField(max_length=52)),
                ('bugDescription', models.TextField()),
                ('attachments', models.FileField(upload_to=None)),
            ],
        ),
    ]
