# Generated by Django 4.0.5 on 2022-07-13 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0002_alter_bug_assignto_alter_bug_attachments_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='assignTo',
            new_name='assignedTo',
        ),
    ]
