# Generated by Django 4.0.5 on 2022-07-21 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0003_rename_assignto_bug_assignedto'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='slug',
            field=models.SlugField(default='', max_length=200, unique=True),
        ),
    ]
