# Generated by Django 4.0.5 on 2022-07-22 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0004_bug_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bug',
            name='slug',
        ),
    ]
